### ISSUE TITLE
No dependency named react-dom/client

### ISSUE THREAD

**Issue by bhlieberman** [lilactown/helix#108]
I am following along with the minimal example in the README. I have installed react-dom using `npm install react-dom`. But when I evaluate any namespace that requires it like
```
(ns foo
(:require ["react-dom/client" :as rdom]))
```
I receive this error: 
```
The required JS dependency "react-dom/client" is not available, it was required by "app/core.cljs".
```
I started my project using `npx create-cljs-app` and I am running Windows 11 and the Eclipse JDK. (I was using WSL but was having issues with hot reloading both JS and CLJS projects so I've started running the watch on Windows.)

**Comment by lilactown** [comment]
What version of React are you using?

**Comment by bhlieberman** [comment]
16.8.0. I'm guessing I should update

**Comment by lilactown** [comment]
Yeah, `react-dom/client` is new in React 18. Upgrading to that should fix the issue.
