### ISSUE TITLE
Confusing syntax with `wrap` and args destructuring

### ISSUE THREAD

**Issue by lilactown** [lilactown/helix#110]
Ran into this in a PR last week, where someone had originally done

```clojure
(defnc my-component
  [{:keys [foo bar]}]
  {:wrap (with-baz #(str foo bar))}
  ,,,)
```

Which syntactically looks right, but actually `foo bar` aren't destructured until after `with-baz` is called to wrap the component. The author corrected their code, but I was confused why they changed it!

Perhaps we should move the `:wrap` metadata above the args so that it's clearer what's in scope?

```clojure
(defnc my-component
  {:wrap (with-baz #(str (:foo %) (:bar %))}
  [{:keys [foo bar]}]
  ,,,)
```

**Comment by dvingo** [comment]
:+1 This is also aligned with metadata forms on `defn`
