### ISSUE TITLE
`wrap-fx` is public

### ISSUE THREAD

**Issue by SevereOverfl0w** [lilactown/helix#127]
https://github.com/lilactown/helix/blob/cc88c8ccfd73fa8e4ac803dd2dcf9115ac943a89/src/helix/hooks.cljc#L122-L129

Is this intentional?  It has no docstring, and I think it's only supposed to be for internal use by `use-effect`

**Comment by lilactown** [comment]
not really. if we make it public, will the macroexpansion of `use-effect` cause compiler warnings?
