### ISSUE TITLE
Companies using Helix

### ISSUE THREAD

**Issue by rome-user** [lilactown/helix#138]
This should probably be a discussion instead, but it would be cool if some users of Helix can mention whether they use Helix at their workplace. After seeing an awesome Clojure/conj talk in person and hearing many people using Helix, this library is a lot more "battle tested" than someone may initially think.

Mentioning a few companies or open source apps in the README would be good, in my opinion

**Comment by lilactown** [comment]
Sure! If people want to open a PR with their logo, I'm happy to add them. I added Amperity (my employer) to the README
