### ISSUE TITLE
indent metadata on helix.dom macros

### ISSUE THREAD

**Issue by rome-user** [lilactown/helix#142]
The CIDER plugin for Emacs allows one to use metadata to express indentation of macros and functions in a portable manner. It seems that this is already done for some macros, such as `defcomponent` and `$`. We should consider using an indent metadata.

At the moment, here is an example of current indentation in Emacs.
```clojure
(d/table
 (d/thead
  (d/tr {:scope "row"}
        (d/th "one")
        (d/th "two")))
 (d/body
  (d/tr
   (d/td "1")
   (d/td "2"))))
```

By using `:style/indent [:defn]` metadata on the declared vars, we can achieve the following indentation.

```clojure
(d/table
  (d/thead
    (d/tr {:scope "row"}
      (d/th "one")
      (d/th "two")))
  (d/body
    (d/tr
      (d/td "1")
      (d/td "2"))))
```

Implementing this is tricky, since we need a macro that can `declare` vars with the appropriate metadata in both Clojure and ClojureScript. Since the `helix.dom` namespace currently reserves a few symbols, I made a macro in a separate namespace. It looks like this.

```clojure
(defmacro declare-indented [& syms]
  `(do 
     ~@(map (fn [sym]
              `(declare ~(vary-meta sym assoc :style/indent [:defn])))
            syms)))
```

**Comment by lilactown** [comment]
Personally, I don't mind the normal indentation and I make do by always putting the props map on a new line if an element also takes children, e.g.

```clojure
(d/table
 (d/thead
  (d/tr
   {:scope "row"}
   (d/th "one")
   (d/th "two")))
 (d/body
  (d/tr
   (d/td "1")
   (d/td "2"))))
```

We've been using that as an informal style requirement at my work for awhile.

I'm also not sure that all editors consume these style metadata the same way; I know I've seen special casing having to be done in IntelliJ.

I can think about if this is something I want to change for us internally and try and get adoption in non-Emacs editors. In the meantime, if you prefer the way it's indented in your second snippet, could that be something configurable on a per-project basis?

**Comment by lilactown** [comment]
that's very strange. I'm using clojure-mode from 2023-06-26 and I don't see this.
