### ISSUE TITLE
`helix.dom/tags` removed

### ISSUE THREAD

**Issue by rschmukler** [lilactown/helix#152]
Hey! Seems like the [style indent PR](https://github.com/lilactown/helix/pull/148) commented out `helix.dom/tags`. This caused my `defc` wrapper macro to break as I was relying on it.

Is this something that was intentional or are you open to re-adding it to help maintain API stability? Otherwise I could also just use `ns-externs` but ironically, the `gen-tag` macro still remains

**Comment by lilactown** [comment]
@rschmukler I didn't think that anyone would rely on the `helix.dom/tags` var. What exactly are you using it for?

I'm tempted to clean up the `gen-tag` function and the rest of the code. You could use `ns-externs`, but you'll also have to filter out `$d`

**Comment by rschmukler** [comment]
I prefer hiccup to the macros so I am building a mappings of keywords to helix.dom macros in my own defc wrapper. Eg. :h1 resolves to helix.dom/h1 by the time the macro is done expanding. 

I was doing that by iterating the tags, but using ns-externs works just as well.
