### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by rome-user** [lilactown/helix#154]
Warnings from shadow-cljs when compiling namespaces using helix breaks some Emacs functionality, like compiling an new ns form and having it exist in the runtime. Not sure why this happens, but it happens whenever the CLJS compiler emits a warning. It interrupts REPL-driven development for me.

I know there is an outstanding issue regarding the refactoring of the `$` macros. But for the time being I would like a `0.2.1` release.

**Comment by lilactown** [comment]
Just released 0.2.1 with the fix for extending symbol to be printable
