### ISSUE TITLE
Fallback to goog.object/extend when Object.assign is not available (IE11)

### ISSUE THREAD

**Issue by lucywang000** [lilactown/helix#44]
https://github.com/Lokeh/helix/blob/ba87bdb5bf43d8b9f59d727d15615b139c8ea3b8/src/helix/impl/props.cljc#L72-L73

Or at least document that helix doesn't support IE.

**Comment by Lokeh** [comment]
Good callout. I'll fix this soon; also would accept a PR!

**Comment by lilactown** [comment]
This is fixed
