### ISSUE TITLE
Anonymous components (aka `fnc`)

### ISSUE THREAD

**Issue by SevereOverfl0w** [lilactown/helix#83]
We discussed on slack a little while ago.  This would be useful for something we're working on right now (dynamic dispatch of components based on server-side information) so I thought I'd create an issue to track it.

We're able to work without the anonymous stuff for now, so no urgency from my side.

**Comment by lilactown** [comment]
I'm on board. I'll see if I can tackle it soon. Otherwise contributions, welcome!

**Comment by lilactown** [comment]
Added in 4116ce4525728ec2e70b7f2e26a06a8ec539ecbf
