### ISSUE TITLE
displayName should be static in defcomponent

### ISSUE THREAD

**Issue by tomconnors** [lilactown/helix#92]
It looks like `defcomponent` should set "displayName" with the statics rather than w/ the instance methods/properties. 

This gives me a component that uses `HelixComponent` as its display name:
``` clojure
(h/defcomponent MyComponent
  (render [this] (helix.dom/div)))
```
but this gives me one w/ `MyComponent` as the display name:
``` clojure
(h/defcomponent MyComponent
  ^:static (displayName "MyComponent")
  (render [this] (helix.dom/div)))
```

**Comment by lilactown** [comment]
ah yep! should be an easy fix

**Comment by lilactown** [comment]
Fixed in latest master! Thanks for the report
